version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_USER: arte_database_user
      DB_PASS: PMgMMgOHG1WkVkIBLuu2J94WDtUI1PJ1
      DB_NAME: arte_database

  db:
    image: mysql:8.0
    container_name: arte_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arte_database
      MYSQL_USER: arte_database_user
      MYSQL_PASSWORD: PMgMMgOHG1WkVkIBLuu2J94WDtUI1PJ1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: